PresentacionAdmin/Controllers/AccesoController.cs
using Entidad;
using Negocios;
using System.Linq;
using System.Web.Mvc;

namespace PresentacionAdmin.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult CambiarClave()
        {
            return View();
        }

        public ActionResult RestablecerClave()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string correo, string clave)
        {
            Usuario oUsuario = new Usuario();
            oUsuario = new N_Usuarios().Listar().Where(u => u.correo == correo && u.clave == N_Recursos.ConvertitSha256(clave)).FirstOrDefault();
            if (oUsuario == null)
            {
                ViewBag.Error = "Correo o contraseña no son validos";
                return View();
            }
            else
            {
                ViewBag.Error = null;
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

PresentacionAdmin/Views/Acceso/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Iniciar Sesion- Sistema Farmacia</title>
    <link rel="shortcut icon" href="~/assets/images/icono.png">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/Content/login.min.css" rel="stylesheet" />
    <link href="~/Content/login-fontawesome.min.css" rel="stylesheet" />
</head>
<body class="bg-gradient-primary">

    <div class="container py-lg-2">

        <!-- Outer Row -->
        <div class="row justify-content-center py-lg-4">

            <div class="col-xl-12 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row py-lg-5" style="user-select: none;">
                            <div class="col-lg-6 d-none d-lg-block">
                                <img src="~/assets/login/fondo.svg" class="img-fluid"/>
                            </div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bienvenido Farmadev!</h1>
                                    </div>
                                    <form class="user" action="@Url.Action("Login", "Acceso")" method="post">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" name="correo" placeholder="correo@algo.com">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user" name="clave" placeholder="Contraseña">
                                        </div>
                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Iniciar Sesion
                                        </button>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="h6" href=" " style="text-decoration: none;">Restablecer Contraseña?</a>

                                    </div>
                                    <div class="text-center">
                                        <a class="h6" href=" " style="text-decoration: none;">Crear Cuenta!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/login-bootstrap.bundle.min.js"></script>
    <script src="~/Scripts/login-jquery.easing.min.js"></script>
    <script src="~/Scripts/login-jquery.min.js"></script>
    <script src="~/Scripts/login.js"></script>
</body>
</html>